version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules

# Kita nonaktifkan backend & mongo sementara agar tidak error saat build
# karena belum ada data yang perlu disimpan di database untuk tahap awal.
